config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :buddies do
    # post "buddies", to: "buddies#destroy", as: :destroy
    resources :events, only: %i[index show] do
      member do
        patch :accept
        patch :decline
      end
    end
    post "events", to: "events#create", as: :create_reservation
  end

  resources :events, only: [:destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  CATEGORY = ['all', 'celebrations', 'workout', 'work', 'love', 'holidays']
  include PgSearch::Model

  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  belongs_to :user
  has_many :events, dependent: :destroy
  validates :description, length: { minimum: 10 }, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY, message: '%{value} is not a valid category' }
  validates :city, presence: true

  pg_search_scope :global_search,
                    against: [ :category, :city ],
                    associated_against: {
                      user: [ :name, :age, :sex ]
                    },
                    using: { tsearch: { prefix: true } }


  def unavailable_dates
    events.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :buddy

  validates :user, presence: true

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  SEX = ['female', 'male']
  has_many :buddies
  has_many :events
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :sex, inclusion: { in: SEX, message: '%{value} is not a valid category' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:home, :index]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name age sex])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name age sex])
  end

end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  before_action :set_buddy, only: %i[edit update show destroy]
  before_action :user_connected, only: [:index, :show, :edit, :new]

  def index
    @buddies = Buddy.all
    if params[:query].present?
      @buddies = Buddy.global_search(params[:query])
    else
      @buddies = Buddy.all
    end
    # @buddies = FBuddy.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = @buddies.geocoded.map do |buddy|
      {
        lat: buddy.latitude,
        lng: buddy.longitude,
        info_window: render_to_string(partial: "info_window", locals: {buddy: buddy})
      }
    end
  end

  def show
    @event = Event.new
  end

  def new
    @buddy = Buddy.new
  end

  def create
    @buddy = Buddy.new(buddy_params)
    @buddy.user = current_user
    if @buddy.save
      redirect_to buddy_path(@buddy)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @buddy.update(buddy_params)
      redirect_to buddy_events_path(@buddy)
    else
      render :new
    end
  end

  def destroy
    @buddy.destroy
  end

  private

  def user_connected
    @user = current_user
  end

  def set_buddy
    @buddy = Buddy.find(params[:id])
  end

  def buddy_params
    params.require(:buddy).permit(:description, :category, :city)
  end
end


# OR user.buddy.name @@ :query
# OR user.buddy.sex @@ :query

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :destroy]

  def index
    @buddy = Buddy.find(params[:buddy_id])
    @events = current_user.events
    @buddies = current_user.buddies
    @user = current_user
  end

  def show; end

  def create
    @event = Event.new
    @buddy = Buddy.find(params[:buddy_id])
    @event.user = current_user
    @event.buddy = @buddy
    @event.start_date = params[:event]["start_date"].split("to")[0]
    @event.end_date = params[:event]["start_date"].split("to")[1]
    if @event.save!
      redirect_to buddy_events_path
    else
      render buddy_path(@buddy), status: :unprocessable_entity
    end
  end


  def accept
    @event = Event.find(params[:id])
    @buddy = Buddy.find(params[:buddy_id])
    @event.status = "Accepted"
    @event.save!

    redirect_to buddy_events_path(@buddy, @event)
  end

  def decline
    @event = Event.find(params[:id])
    @buddy = Buddy.find(params[:buddy_id])
    @event.status = "Declined"
    @event.save!

    redirect_to buddy_events_path(@buddy, @event)
  end

  def destroy
    @event.destroy
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  # def event_params
  #   params.require(:event).permit(:status)
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buddies/_info_window.html.erb
<div class= "image-popup">
  <%= cl_image_tag(buddy.user.photo.key) %>
</div>
<div class= "text-popup">
  <div class= "description-popup">
    <h3><%= buddy.user.name %></h3>
    <p>📍<%= buddy.city %></p>
    <% if buddy.user.sex == "male" %>
                  <p> 👨 <%= buddy.user.sex %></p>
                  <% else %>
                  <p> 👩  <%= buddy.user.sex %></p>
                  <% end %>
    <p>👉 <%= buddy.category %></p>
  </div>
  <div class="d-flex justify-content-center">
              <%= link_to "choose", buddy_path(buddy), class:"btn-choose text-center"%>
            </div>
</div>

app/views/buddies/edit.html.erb
<div class="container mt-4">
  <br>

  <div class="row">
    <div class="col-6 m-auto">
      <div class="buddy-form">
          <h1>Update your profile !</h1>
        <br>
          <div class="class mt-3">
            <%= simple_form_for @buddy do |f| %>
              <%= f.input :description %>
              <%= f.input :category, collection: Buddy::CATEGORY %>
              <%= f.input :city %>
              <%= f.input :photo, as: :file %> <br>
              <%= f.button :submit  %>

            <% end %>
            <br>
          </div>
      </div>
    </div>
  </div>

</div>

app/views/buddies/index.html.erb
<div class="banner-buddies">

  <div class= "container-buddies container"  data-controller="cards">
    <div class= "title-margin">
      <h1 class="h1-size">Find the best buddy for your event</h1>
      <p>Select among all the following buddies the one who will come with you to your event. All our buddies' profiles are verified</p>
    </div>

<%= form_with url: buddies_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a buddy"
  %>
  <%= submit_tag "Search", class: "btn-search" %>
<% end %>

<div class= "cards-map d-flex">

  <div class="all-cards-buddies">
    <% @buddies.each do |buddy| %>
        <div class="card-buddy">
           <%= cl_image_tag(buddy.user.photo.key) %>
          <div class="card-buddy-infos">
           <h3><%= buddy.user.name %></h3>
            <div class="buddy.description">
               <% if buddy.user.sex == "male" %>
              <p> 👨 <%= buddy.user.sex %></p>
              <% else %>
              <p> 👩 <%= buddy.user.sex %></p>
              <% end %>
              <p>📍 <%= buddy.city %></p>
              <p> 👉 available for: <%= buddy.category %></p>
            </div>
            <div class="d-flex justify-content-center">
              <%= link_to "choose", buddy_path(buddy), data: { turbolinks: false }, class:"btn-choose text-center"%>
            </div>
          </div>
        </div>
      <% end %>
  </div>

    <div style="width: 100%; height: 600px;"
    class = "map-style"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

  <%# CATEGORY = ['all', 'celebrations', 'workout', 'work', 'love', 'holidays'] %>

app/views/buddies/new.html.erb
<div class="container mt-4">
  <br>

  <div class="row">
    <div class="col-6 m-auto">
      <div class="buddy-form">
          <h1>Join the community of buddies !</h1>
        <br>
          <div class="class mt-3">
            <%= simple_form_for @buddy do |f| %>
              <%= f.input :description %>
              <%= f.input :category, collection: Buddy::CATEGORY %>
              <%= f.input :city %>
              <%= f.input :photo, as: :file %> <br>
              <%= f.button :submit %>
            <% end %>
            <br>
          </div>
      </div>
    </div>
  </div>

</div>

app/views/buddies/show.html.erb
<div class="container-show">
  <div class="profile grow">
    <div class="center-image">
        <div class="image">
          <%= cl_image_tag(@buddy.user.photo.key,:width => 300, :height => 300, :crop => :fill) %>
        </div>
        <div class="name">
          <h2><%= @buddy.user.name %></h2>
        </div>
        <div class="age">
          <p><strong><%= @buddy.user.age %></strong> years old</p>
        </div>
        <div class="category">
         <p>Available for <strong><%= @buddy.category %></strong> events !</p>
        </div>
        <div class="description">
          <p>"<%= @buddy.description %>!"</p>
        </div>
        <div class="city">
         <p>📍<strong><%= @buddy.city %></strong></p>
        </div>
        <div id='buddy-event-dates' data-unavailable="<%= @buddy.unavailable_dates.to_json %>">
          <% if current_user.id != @buddy.user_id  %>
            <%= simple_form_for([@buddy, @event]) do |f| %>
            <%= f.input :start_date, as: :string, type: :text %>
            <%= f.submit "Have fun with #{@buddy.user.name}", class: "btn-back" %>
            <% end %>
          <% end %>
        </div>
        <div class="buttons">
          <div class="btn-back">
            <%= link_to "Back to list", buddies_path, class: "btn-back" %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container-dash">
  <div class="cards-dash">


    <div class="content-profile">
      <div class="me">
        <div class="h2-user-profile"><h2><strong>My user profile</strong></h2></div> <br>
          <div class="image">
            <%= cl_image_tag @user.photo.key,  :width=> 150, :height=> 150, :gravity=> :face, :radius=> :max, :crop=> :fill %>
          </div> <br>
          <div class="infos">
            <h3><strong><%= @user.name %></strong></h3>
            <p><%= @user.age %> years old </p>
              <% if @user.sex == "male" %>
                  <p> 👨 <%= @user.sex %></p>
                  <% else %>
                  <p> 👩  <%= @user.sex %></p>
                  <% end %>
          </div>
          <% @buddies.each do |buddy| %>
            <div class="description-user">
              <p>📍<%= buddy.city %> 🇫🇷 </p> <br>
              <p><em><%= buddy.description %></em></p> <br>
              <p>I am available for : <%= buddy.category %></p>
            </div>
            <div class="bouton1-profil-user">
            <%= link_to "Update my buddy profile", edit_buddy_path(buddy), class:"btn-choose" %> <br>
            </div>
            <div class="bouton2-profil-user">
            <%= link_to "Delete my buddy profile", buddy_path(buddy), class:"btn-choose", data: { turbo_confirm: "Are you sure you want to cancel", turbo_method: :delete} %> <br>
            </div>
          <% end %>
      </div>
    </div>


    <div class= "content-resa">
      <div class="me-buddy">
        <div class= "text-center">
          <div class="h2-user-profile"><h2><strong>My reservations</strong></h2>
          </div> <br>
          <%# <h5>Here's the buddy you chose : 🤜 🤛  </h5> %>
          <h5>Here's the buddy</h5><h5><strong>you chose</strong> : 🤜 🤛  </h5>
        </div>
        <% unless @events.empty? %>
          <div class="all-cards-buddies-resa">
              <div class="contour-buddy">
                <% @events.each do |event| %>
                  <div class="card-buddy">
                    <%= cl_image_tag event.buddy.user.photo.key %>
                    <div class="card-buddy-infos-dash">
                      <%= event.buddy.user.name %> <br>
                      📍<%= event.buddy.city %>
                      <br>
                      <%= link_to "Cancel", event_path(event), class:"btn-choose", data: { turbo_confirm: "Are you sure you want to decline", turbo_method: :delete} %>
                    </div>
                  </div>
                <% end %>
              </div>
          </div>
        <% else %>
        <p>No reservations yet</p>
          <%= link_to "Back to the buddy list", buddies_path, class:"btn-choose" %>
        <% end %>
      </div>
    </div>



    <div class= "content-resa">

      <div class="me-buddy">
        <div class= "text-center">
          <div class="h2-user-profile"><h2><strong>My bookings</strong></h2>
          </div> <br>
          <%# <h5>Here's the buddy you chose : 🤜 🤛  </h5> %>
          <h5>Here's the buddy who</h5><h5><strong>chose you</strong> : 🤜 🤛  </h5>
        </div>
        <p>No booking yet</p>
          <%= link_to "Back to the buddy list", buddies_path, class:"btn-choose" %>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuddyMe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <% unless params[:controller] == 'pages' && params[:action] == 'home' %>
    <%= render "shared/navbar" %>
    <% end %>
    <style>
      body { background: rgb(240,240,240)}
    </style>

    <%= yield %>

    <% unless params[:controller] == 'pages' && params[:action] == 'home' %>
    <%# <% unless params[:controller] == 'buddies' && params[:action] == 'new' %>
    <%# <%= render "shared/footer" %>
    <% end %>

  </body>
</html>

app/views/pages/accept.html.erb
<h1>Pages#accept</h1>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.prismic.io/yubo/6118791b-2978-4f39-bc06-0d5d43cd6e93_LargeGraphics.webp?auto=compress,format&rect=0,0,1600,900&w=1680&h=945);">
  <div class="container banner">
      <h1><strong>GET FRIENDS</strong></h1> <br>
      <%# <h1><strong>GET REAL</strong></h1> <br> %>
      <h1><strong>EASILY</strong></h1> <br>
      <h1><strong>FROM EVERYWHERE</strong></h1> <br>
      <%# <h1>BuddyMe finds you the <strong>best friends</strong> for <strong>life</strong>!</h1> %>
      <%# <p>Explore the app and find your best partner for your event.</p> %>
    <div class="button-home">
      <%= link_to "LET'S GO", buddies_path, class:"btn-home" %>
    </div>

  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        BuddyMe is made with ❤️ at Marseille bébé
      </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="logo">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "tinder-icon-logo-black-and-white.png" %>
      <% end %>
      <p><strong>BuddyMe</strong></p>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Become buddy", new_buddy_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Buddy list", buddies_path, class: "nav-link" %>
          </li>
          <%# <li class="nav-item">
            <%= link_to "Location", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item dropdown">
            <%= cl_image_tag @user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
               <%= link_to "Dashboard", buddy_events_path(@user), class: "dropdown-item"%>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>